import Head from "next/head";
import { QueryClientProvider, QueryClient } from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import CssBaseline from "@mui/material/CssBaseline";
import { Layout } from "@/components";
import { FC } from "@/models";

const queryClient = new QueryClient();

const Provider = ({ children }: FC) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <QueryClientProvider client={queryClient}>
        <Layout>{children}</Layout>
        <ReactQueryDevtools />
        <CssBaseline />
      </QueryClientProvider>
    </>
  );
};
export default Provider;
